CREATE TABLE IF NOT EXISTS cliente (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL,
  telefone VARCHAR(30)
);
CREATE TABLE IF NOT EXISTS servico (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  preco DECIMAL(10,2) NOT NULL
);
CREATE TABLE IF NOT EXISTS agendamento (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  cliente_id BIGINT NOT NULL,
  data DATE NOT NULL,
  horario TIME NOT NULL,
  servico_id BIGINT NOT NULL,
  observacoes VARCHAR(255),
  CONSTRAINT fk_cli FOREIGN KEY (cliente_id) REFERENCES cliente(id),
  CONSTRAINT fk_srv FOREIGN KEY (servico_id) REFERENCES servico(id)
);
CREATE TABLE IF NOT EXISTS contato_mensagem (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL,
  mensagem TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
